### ISSUE TITLE
The package name doesn't have emojis

### ISSUE THREAD

**Issue by mschauer** [theogf/WatchJuliaBurn.jl#20]
So rename to ⌚∴🔥.jl!
Came up in #19. I don't know if this interferes with the registry.

**Comment by theogf** [comment]
> The package name should start with a capital letter, contain only ASCII alphanumeric characters, contain a lowercase letter, be at least 5 characters long, and should not start with "Ju" or contain the string "julia".

We are breaking all the rules! Does it mean they cancel out?

**Comment by theogf** [comment]
I think we did what we could! At least the README is in emojis
